name: Development Build

on:
  push:
    branches: [ dev ]
    tags:
      - 'v*-beta.*'
      - 'v*-rc.*'
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-mock
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=src/csvlotte --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build-test-windows:
    runs-on: windows-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PyInstaller
    
    - name: Test build
      run: |
        python embed_readme.py
        python build.py
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: csvlotte-windows-dev
        path: dist/
        retention-days: 7

  build-test-linux:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PyInstaller
    
    - name: Test build
      run: |
        python embed_readme.py
        python build.py
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: csvlotte-linux-dev
        path: dist/
        retention-days: 7

  build-test-macos:
    runs-on: macos-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PyInstaller
    
    - name: Test build
      run: |
        python embed_readme.py
        python build.py
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: csvlotte-macos-dev
        path: dist/
        retention-days: 7
